### ISSUE TITLE
如果部署到非顶级目录，很多路径引用都是错误的

### ISSUE THREAD

**Issue by cgx739991089** [imsyy/DailyHot#18]
pnpm build之后产生的dist文件夹内的文件上传到网站目录例如xxx.com/hotnews/目录下，很多文件引用都是通过顶级目录引用的(例如：xxx.com/logo.png)，不是通过当前目录引用的，希望可以修复

**Comment by imsyy** [comment]
@cgx739991089 已支持配置站点目录，可以前往 `.env` 文件中配置

**Comment by cgx739991089** [comment]
> @cgx739991089 已支持配置站点目录，可以前往 `.env` 文件中配置

配置全局目录VITE_DIR为“/ceshi/”
部署到xxx.com/ceshi/目录下之后，访问url:xxx.com/ceshi，最后url会变为“xxx.com/ceshi#/”  这个#的位置是否有问题呢

**Comment by imsyy** [comment]
> > @cgx739991089 已支持配置站点目录，可以前往 `.env` 文件中配置
> 
> 配置全局目录VITE_DIR为“/ceshi/” 部署到xxx.com/ceshi/目录下之后，访问url:xxx.com/ceshi，最后url会变为“xxx.com/ceshi#/” 这个#的位置是否有问题呢

没有问题
